url: https://hazy-oracles.github.io/
baseurl: /hazy-oracle-homepage/

# Site settings
title: Effective Human-Machine Teaming with Multimodal Hazy Oracle Models
email: sychun@snu.ac.kr
description: "A principled framework for human–machine teaming that models human ambiguity through multimodal hazy oracle models, enabling adaptive deferral, query generation, and continual co-learning in uncertain environments."

people:
- name: Aidan Dempster
  pic: aidan
  position: Master’s Student of EECS, University of Michigan
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/aidan-dempster-4b3444179/

- name: Byung Hyun Lee
  pic: byunghyun
  position: PhD Candidate of ECE, Seoul National University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/bh-lee/
    - title: home
      url: https://hyun1a.github.io/

- name: Gwanghyun Kim
  pic: gwanghyun
  position: PhD Candidate of ECE, Seoul National University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/gwanghyun-bradley-kim/
    - title: home
      url: https://gwang-kim.github.io

- name: Hayeon Kim
  pic: hayeon_sq
  position: PhD Candidate of ECE, Seoul National University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/hayeon-kim-khy5630/
    - title: home
      url: https://janeyeon.github.io

- name: Hoigi Seo
  pic: hoigi
  position: PhD Candidate of ECE, Seoul National University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/hoigiseo/
    - title: home
      url: https://seohoiki3215.github.io

- name: Jason Corso
  pic: jason
  position: Professor of Robotics, EECS, University of Michigan (PI, US Team)
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jason-corso/
    - title: home
      url: https://web.eecs.umich.edu/~jjcorso/

- name: Jiha Jang
  pic: jiha
  position: PhD Candidate of ECE, Seoul National University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jihajang/
    - title: home
      url: https://jeeit17.github.io

- name: Se Young Chun
  pic: seyoung
  position: Professor of ECE, Seoul National University (PI, Korean Team)
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sychun-953593206/
    - title: home
      url: https://icl.snu.ac.kr/home

- name: Seunggyu Lee
  pic: seunggyu
  position: PhD Candidate of ECE, Seoul National University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/seunggyu-lee-18163b263/

- name: Yayuan Li
  pic: yayuan
  position: PhD Candidate of EECS, University of Michigan
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/yayuan-li-148659272/
    - title: github
      url: https://github.com/yayuanli

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 301 Building, 1 Gwanak-ro
  - line: Gwanak-gu, Seoul 08826, South Korea

# Build settings
markdown: kramdown
permalink: pretty